"use strict";

const logger = require("../src/infrastructure/logging/logger");
const { generateDppRecordId } = require("../src/shared/identifiers/dpp-record-id");
const { recordSignedDppRelease } = require("../src/infrastructure/audit/dpp-release-record-service");
const {
  extractCarrierAuthenticityMutation,
  applyCarrierAuthenticityMutation,
  buildCarrierAuthenticityResponseFields,
  normalizeCarrierAuthenticityMetadata,
  validateQrPrintSpecification,
} = require("../src/shared/passports/carrier-authenticity");
const registerApiKeyRoutes = require("../src/modules/passports/register-api-key-routes");
const registerAccessGrantRoutes = require("../src/modules/passports/register-access-grant-routes");
const registerAuditAnalyticsRoutes = require("../src/modules/passports/register-audit-analytics-routes");
const registerBackupRoutes = require("../src/modules/passports/register-backup-routes");
const registerCarrierSecurityRoutes = require("../src/modules/passports/register-carrier-security-routes");
const registerCompanyPassportReadRoutes = require("../src/modules/passports/register-company-passport-read-routes");
const registerBulkLifecycleRoutes = require("../src/modules/passports/register-bulk-lifecycle-routes");
const registerCreateRoutes = require("../src/modules/passports/register-create-routes");
const registerDeleteRoutes = require("../src/modules/passports/register-delete-routes");
const registerHistoryReadRoutes = require("../src/modules/passports/register-history-read-routes");
const registerLifecycleRoutes = require("../src/modules/passports/register-lifecycle-routes");
const registerPreviewManagementRoutes = require("../src/modules/passports/register-preview-management-routes");
const registerPublicApiV1Routes = require("../src/modules/passports/register-public-api-v1-routes");
const registerPassportSupportRoutes = require("../src/modules/passports/register-support-routes");
const registerUpdateRoutes = require("../src/modules/passports/register-update-routes");
const { createApiKeyHelpers } = require("../src/modules/passports/api-key-helpers");
const { createBackupEventHelpers } = require("../src/modules/passports/backup-event-helpers");
const { createCarrierSecurityHelpers } = require("../src/modules/passports/carrier-security-helpers");
const { createComplianceHelpers } = require("../src/modules/passports/compliance-helpers");
const { insertPassportRegistry: insertPassportRegistryWithClient } = require("../src/modules/passports/passport-registry-repository");

module.exports = function registerPassportRoutes(app, {
  pool,
  fs,
  crypto,
  authenticateToken,
  isSuperAdmin,
  checkCompanyAccess,
  checkCompanyAdmin,
  requireEditor,
  requireDraftEditor,
  authenticateApiKey,
  requireApiKeyScope,
  publicReadRateLimit,
  apiKeyReadRateLimit,
  assetWriteRateLimit,
  upload,
  hashSecret,
  createAccessKeyMaterial,
  createDeviceKeyMaterial,
  // passport service helpers
  IN_REVISION_STATUSES_SQL,
  EDITABLE_RELEASE_STATUSES_SQL,
  REVISION_BLOCKING_STATUSES_SQL,
  EDIT_SESSION_TIMEOUT_HOURS,
  EDIT_SESSION_TIMEOUT_SQL,
  IN_REVISION_STATUS,
  SYSTEM_PASSPORT_FIELDS,
  // pure helpers from passport-helpers.js
  getTable,
  getPassportFieldValue,
  normalizePassportRow,
  normalizeReleaseStatus,
  isEditablePassportStatus,
  normalizeInternalAliasIdValue,
  generateInternalAliasIdValue,
  normalizePassportRequestBody,
  extractExplicitFacilityId,
  getWritablePassportColumns,
  getStoredPassportValues,
  joinQuotedSqlIdentifiers,
  toStoredPassportValue,
  coerceBulkFieldValue,
  buildCurrentPublicPassportPath,
  buildInactivePublicPassportPath,
  buildPreviewPassportPath,
  isPublicHistoryStatus,
  // db helpers from passport-service.js
  logAudit,
  getPassportTypeSchema,
  findExistingPassportByInternalAliasId,
  getPassportLineageContext,
  getPassportVersionsByLineage,
  fetchCompanyPassportRecord,
  resolveCompanyPreviewPassport,
  archivePassportSnapshot,
  archivePassportSnapshots,
  updatePassportRowById,
  buildPassportVersionHistory,
  clearExpiredEditSessions,
  listActiveEditSessions,
  markOlderVersionsObsolete,
  verifyAuditLogChain,
  buildAuditLogRootSummary,
  listAuditLogAnchors,
  anchorAuditLogRoot,
  stripRestrictedFieldsForPublicView,
  getCompanyNameMap,
  queryTableStats,
  submitPassportToWorkflow,
  // signing service
  signPassport,
  signPortableDataConstruct,
  buildBatteryPassJsonExport,
  storageService,
  complianceService,
  accessRightsService,
  didService,
  productIdentifierService,
  backupProviderService,
  buildExpandedPassportPayload,
  buildCanonicalPassportPayload,
  createPassportTable = null
}) {
  const insertPassportRegistry = (params = {}) => insertPassportRegistryWithClient({
    ...params,
    client: params.client || pool,
  });

  const ARCHIVED_HISTORY_REASON_SQL = `('before_archive_delete','before_bulk_archive_delete')`;
  const ARCHIVED_HISTORY_FILTER_SQL = `(snapshot_reason IS NULL OR snapshot_reason IN ${ARCHIVED_HISTORY_REASON_SQL})`;
  const {
    buildApiKeyFieldWriteDecision,
    buildApiKeyHashRecord,
    buildApiKeyScopesForAccessMode,
    flattenTypeFields,
    parseApiKeyAccessMode,
    parseApiKeyMaxConfidentiality,
    parseApiKeyOperatorType,
    sanitizePassportForApiKey,
  } = createApiKeyHelpers({ accessRightsService, crypto });
  const {
    getActorIdentifier,
    replicateAccessControlEventToBackup,
    replicateAuditAnchorToBackup,
    replicatePassportToBackup,
    withAuditActorAliases,
  } = createBackupEventHelpers({
    backupProviderService,
    complianceService,
    getCompanyNameMap,
    normalizePassportRow,
  });
  const {
    buildCarrierAuthenticityStorageValue,
    buildDataCarrierVerificationRecord,
    getTrustedViewerHost,
    maybeSignCarrierPayload,
    parseUrlHost,
    recordPassportSecurityEvent,
  } = createCarrierSecurityHelpers({
    pool,
    normalizeReleaseStatus,
    buildCurrentPublicPassportPath,
    buildPreviewPassportPath,
    signPortableDataConstruct,
  });
  const {
    VALID_GRANULARITIES,
    buildComplianceManagedFields,
    buildStoredProductIdentifiers,
    evaluateCompliance,
    getCompanyDppPolicy,
    hasReleasedLineageVersion,
    isFullRepresentationRequest,
    loadCompanySerializationContext,
    loadLatestLivePassport,
    reconcileManagedReleaseFields,
    resolveGranularityForCreate,
  } = createComplianceHelpers({
    pool,
    complianceService,
    productIdentifierService,
    extractExplicitFacilityId,
    getTable,
    getPassportTypeSchema,
    normalizePassportRow,
    normalizeInternalAliasIdValue,
    normalizeReleaseStatus,
    updatePassportRowById,
  });

  // ─── API KEY MANAGEMENT ────────────────────────────────────────────────────

  registerApiKeyRoutes(app, {
    pool,
    logger,
    authenticateToken,
    checkCompanyAdmin,
    logAudit,
    buildApiKeyHashRecord,
    buildApiKeyScopesForAccessMode,
    parseApiKeyAccessMode,
    parseApiKeyOperatorType,
    parseApiKeyMaxConfidentiality,
    replicateAccessControlEventToBackup,
  });

  registerPublicApiV1Routes(app, {
    pool,
    logger,
    authenticateApiKey,
    requireApiKeyScope,
    apiKeyReadRateLimit,
    normalizePassportRequestBody,
    getPassportTypeSchema,
    getTable,
    normalizePassportRow,
    sanitizePassportForApiKey,
    flattenTypeFields,
    buildApiKeyFieldWriteDecision,
    archivePassportSnapshot,
    updatePassportRowById,
    logAudit,
    EDITABLE_RELEASE_STATUSES_SQL,
  });

  // ─── PASSPORT CRUD ─────────────────────────────────────────────────────────

  registerCreateRoutes(app, {
    pool,
    logger,
    authenticateToken,
    checkCompanyAccess,
    requireDraftEditor,
    generateDppRecordId,
    normalizePassportRequestBody,
    getPassportTypeSchema,
    createPassportTable,
    getTable,
    normalizeInternalAliasIdValue,
    generateInternalAliasIdValue,
    getCompanyDppPolicy,
    resolveGranularityForCreate,
    buildStoredProductIdentifiers,
    buildComplianceManagedFields,
    findExistingPassportByInternalAliasId,
    normalizeReleaseStatus,
    SYSTEM_PASSPORT_FIELDS,
    getWritablePassportColumns,
    joinQuotedSqlIdentifiers,
    toStoredPassportValue,
    extractCarrierAuthenticityMutation,
    applyCarrierAuthenticityMutation,
    maybeSignCarrierPayload,
    buildCarrierAuthenticityStorageValue,
    getCompanyNameMap,
    insertPassportRegistry,
    logAudit,
    archivePassportSnapshot,
    getActorIdentifier,
  });

  registerCompanyPassportReadRoutes(app, {
    pool,
    logger,
    authenticateToken,
    checkCompanyAccess,
    normalizePassportRequestBody,
    getTable,
    getPassportFieldValue,
    normalizePassportRow,
    normalizeReleaseStatus,
    normalizeInternalAliasIdValue,
    getPassportTypeSchema,
    fetchCompanyPassportRecord,
    buildBatteryPassJsonExport,
    buildExpandedPassportPayload,
    complianceService,
    productIdentifierService,
    isFullRepresentationRequest,
    loadCompanySerializationContext,
    IN_REVISION_STATUS,
    IN_REVISION_STATUSES_SQL,
    EDITABLE_RELEASE_STATUSES_SQL,
    ARCHIVED_HISTORY_FILTER_SQL,
  });

  registerPreviewManagementRoutes(app, {
    pool,
    authenticateToken,
    checkCompanyAccess,
    requireEditor,
    createAccessKeyMaterial,
    EDIT_SESSION_TIMEOUT_HOURS,
    stripRestrictedFieldsForPublicView,
    getCompanyNameMap,
    normalizePassportRow,
    resolveCompanyPreviewPassport,
    clearExpiredEditSessions,
    listActiveEditSessions,
    buildPreviewPassportPath,
    buildCurrentPublicPassportPath,
    buildInactivePublicPassportPath,
    buildCanonicalPassportPayload,
    didService,
    productIdentifierService,
    logAudit,
  });

  registerUpdateRoutes(app, {
    pool,
    logger,
    authenticateToken,
    checkCompanyAccess,
    requireDraftEditor,
    normalizePassportRequestBody,
    getPassportTypeSchema,
    createPassportTable,
    getTable,
    getWritablePassportColumns,
    getStoredPassportValues,
    normalizeInternalAliasIdValue,
    normalizeReleaseStatus,
    isEditablePassportStatus,
    updatePassportRowById,
    archivePassportSnapshot,
    archivePassportSnapshots,
    getActorIdentifier,
    logAudit,
    EDITABLE_RELEASE_STATUSES_SQL,
    IN_REVISION_STATUSES_SQL,
    VALID_GRANULARITIES,
    hasReleasedLineageVersion,
    buildStoredProductIdentifiers,
    findExistingPassportByInternalAliasId,
    extractCarrierAuthenticityMutation,
    applyCarrierAuthenticityMutation,
    maybeSignCarrierPayload,
    buildCarrierAuthenticityStorageValue,
    getCompanyNameMap,
    buildComplianceManagedFields,
    SYSTEM_PASSPORT_FIELDS,
  });

  registerLifecycleRoutes(app, {
    pool,
    logger,
    authenticateToken,
    checkCompanyAccess,
    requireEditor,
    generateDppRecordId,
    normalizePassportRequestBody,
    getTable,
    normalizeInternalAliasIdValue,
    normalizePassportRow,
    normalizeReleaseStatus,
    findExistingPassportByInternalAliasId,
    buildStoredProductIdentifiers,
    productIdentifierService,
    getPassportLineageContext,
    archivePassportSnapshot,
    archivePassportSnapshots,
    insertPassportRegistry,
    logAudit,
    replicatePassportToBackup,
    loadLatestLivePassport,
    reconcileManagedReleaseFields,
    evaluateCompliance,
    EDITABLE_RELEASE_STATUSES_SQL,
    REVISION_BLOCKING_STATUSES_SQL,
    ARCHIVED_HISTORY_FILTER_SQL,
    markOlderVersionsObsolete,
    complianceService,
    signPassport,
    recordSignedDppRelease,
    getActorIdentifier,
    IN_REVISION_STATUS,
    submitPassportToWorkflow,
    VALID_GRANULARITIES,
  });

  // ─── BULK REVISE ───────────────────────────────────────────────────────────

  registerBulkLifecycleRoutes(app, {
    pool,
    logger,
    authenticateToken,
    checkCompanyAccess,
    requireEditor,
    generateDppRecordId,
    normalizePassportRequestBody,
    getTable,
    normalizeReleaseStatus,
    toStoredPassportValue,
    coerceBulkFieldValue,
    archivePassportSnapshot,
    archivePassportSnapshots,
    insertPassportRegistry,
    logAudit,
    replicatePassportToBackup,
    evaluateCompliance,
    EDITABLE_RELEASE_STATUSES_SQL,
    REVISION_BLOCKING_STATUSES_SQL,
    ARCHIVED_HISTORY_FILTER_SQL,
    markOlderVersionsObsolete,
    signPassport,
    recordSignedDppRelease,
    getActorIdentifier,
    IN_REVISION_STATUS,
    submitPassportToWorkflow,
    getPassportLineageContext,
  });

  registerDeleteRoutes(app, {
    pool,
    logger,
    authenticateToken,
    checkCompanyAccess,
    requireEditor,
    normalizePassportRequestBody,
    getPassportTypeSchema,
    getTable,
    normalizeInternalAliasIdValue,
    normalizeReleaseStatus,
    isEditablePassportStatus,
    findExistingPassportByInternalAliasId,
    archivePassportSnapshot,
    getActorIdentifier,
    logAudit,
    EDITABLE_RELEASE_STATUSES_SQL,
  });

  // ─── DIFF & HISTORY ────────────────────────────────────────────────────────

  registerHistoryReadRoutes(app, {
    pool,
    logger,
    authenticateToken,
    checkCompanyAccess,
    getPassportLineageContext,
    getPassportVersionsByLineage,
    buildPassportVersionHistory,
    productIdentifierService,
  });
  registerPassportSupportRoutes(app, {
    pool,
    crypto,
    logger,
    authenticateToken,
    checkCompanyAccess,
    requireEditor,
    upload,
    storageService,
    logAudit,
    getTable,
    getPassportLineageContext,
    normalizePassportRow,
    isPublicHistoryStatus,
    EDITABLE_RELEASE_STATUSES_SQL,
  });

  registerAuditAnalyticsRoutes(app, {
    pool,
    logger,
    authenticateToken,
    checkCompanyAccess,
    checkCompanyAdmin,
    queryTableStats,
    getTable,
    verifyAuditLogChain,
    buildAuditLogRootSummary,
    listAuditLogAnchors,
    anchorAuditLogRoot,
    withAuditActorAliases,
    replicateAuditAnchorToBackup,
    ARCHIVED_HISTORY_FILTER_SQL,
  });

  registerAccessGrantRoutes(app, {
    pool,
    accessRightsService,
    authenticateToken,
    checkCompanyAccess,
    checkCompanyAdmin,
    logAudit,
    replicateAccessControlEventToBackup,
  });
  registerBackupRoutes(app, {
    backupProviderService,
    authenticateToken,
    isSuperAdmin,
    checkCompanyAccess,
    checkCompanyAdmin,
    logAudit,
    loadLatestLivePassport,
    normalizePassportRow,
    stripRestrictedFieldsForPublicView,
    getCompanyNameMap,
    replicatePassportToBackup,
  });
  registerCarrierSecurityRoutes(app, {
    pool,
    crypto,
    authenticateToken,
    checkCompanyAccess,
    requireEditor,
    publicReadRateLimit,
    hashSecret,
    createDeviceKeyMaterial,
    logAudit,
    normalizePassportRequestBody,
    getTable,
    normalizePassportRow,
    getCompanyNameMap,
    extractCarrierAuthenticityMutation,
    applyCarrierAuthenticityMutation,
    buildCarrierAuthenticityResponseFields,
    normalizeCarrierAuthenticityMetadata,
    validateQrPrintSpecification,
    maybeSignCarrierPayload,
    buildCarrierAuthenticityStorageValue,
    buildDataCarrierVerificationRecord,
    recordPassportSecurityEvent,
    getTrustedViewerHost,
    parseUrlHost,
  });

};
