"use strict";

const registerAssetManagementLaunchRoutes = require("../../routes/asset-management-launch");
const registerRepositoryRoutes = require("../../routes/repository");
const registerNotificationRoutes = require("../../routes/notifications");
const registerMessagingRoutes = require("../../routes/messaging");
const registerWorkflowRoutes = require("../../routes/workflow");
const registerHealthRoutes = require("../../routes/health");
const registerAuthRoutes = require("../../routes/auth");
const registerAdminRoutes = require("../../routes/admin");
const registerAssetManagementApiRoutes = require("../../routes/asset-management-api");
const registerPassportRoutes = require("../../routes/passports");
const registerPassportPublicRoutes = require("../../routes/passport-public");
const registerCompanyRoutes = require("../../routes/company");
const registerDppApiRoutes = require("../../routes/dpp-api");
const registerDictionaryRoutes = require("../../routes/dictionary");

function registerAppRoutes(app, deps) {
  registerAssetManagementLaunchRoutes(app, {
    authenticateToken: deps.authenticateToken,
    checkCompanyAccess: deps.checkCompanyAccess,
    requireEditor: deps.requireEditor,
    assertAssetManagementEnabled: deps.assertAssetManagementEnabled,
    generateAssetLaunchToken: deps.generateAssetLaunchToken,
    ASSET_SHARED_SECRET: deps.ASSET_SHARED_SECRET,
  });

  registerRepositoryRoutes(app, {
    pool: deps.pool,
    fs: deps.fs,
    path: deps.path,
    publicReadRateLimit: deps.publicReadRateLimit,
    authenticateToken: deps.authenticateToken,
    checkCompanyAccess: deps.checkCompanyAccess,
    requireEditor: deps.requireEditor,
    repoUpload: deps.repoUpload,
    repoSymbolUpload: deps.repoSymbolUpload,
    REPO_BASE_DIR: deps.REPO_BASE_DIR,
    isPathInsideBase: deps.isPathInsideBase,
    storageService: deps.storageService,
  });

  registerNotificationRoutes(app, { pool: deps.pool, authenticateToken: deps.authenticateToken });
  registerMessagingRoutes(app, { pool: deps.pool, authenticateToken: deps.authenticateToken });

  registerWorkflowRoutes(app, {
    pool: deps.pool,
    authenticateToken: deps.authenticateToken,
    checkCompanyAccess: deps.checkCompanyAccess,
    requireEditor: deps.requireEditor,
    submitPassportToWorkflow: deps.submitPassportToWorkflow,
    getTable: deps.getTable,
    IN_REVISION_STATUS: deps.IN_REVISION_STATUS,
    signPassport: deps.signPassport,
    markOlderVersionsObsolete: deps.markOlderVersionsObsolete,
    logAudit: deps.logAudit,
    buildCurrentPublicPassportPath: deps.buildCurrentPublicPassportPath,
    createNotification: deps.createNotification,
    complianceService: deps.complianceService,
    archivePassportSnapshot: deps.archivePassportSnapshot,
    renderInfoTable: deps.renderInfoTable,
  });

  registerAuthRoutes(app, {
    pool: deps.pool,
    jwt: deps.jwt,
    JWT_SECRET: deps.JWT_SECRET,
    hashPassword: deps.hashPassword,
    verifyPassword: deps.verifyPassword,
    verifyPasswordAndUpgrade: deps.verifyPasswordAndUpgrade,
    generateToken: deps.generateToken,
    hashOpaqueToken: deps.hashOpaqueToken,
    validatePasswordPolicy: deps.validatePasswordPolicy,
    PASSWORD_MIN_LENGTH: deps.PASSWORD_MIN_LENGTH,
    hashOtpCode: deps.hashOtpCode,
    generateOtpCode: deps.generateOtpCode,
    SESSION_COOKIE_NAME: deps.SESSION_COOKIE_NAME,
    setAuthCookie: deps.setAuthCookie,
    clearAuthCookie: deps.clearAuthCookie,
    sendOtpEmail: deps.sendOtpEmail,
    createTransporter: deps.createTransporter,
    brandedEmail: deps.brandedEmail,
    renderInfoTable: deps.renderInfoTable,
    logAudit: deps.logAudit,
    authRateLimit: deps.authRateLimit,
    otpRateLimit: deps.otpRateLimit,
    passwordResetRateLimit: deps.passwordResetRateLimit,
    publicReadRateLimit: deps.publicReadRateLimit,
    authenticateToken: deps.authenticateToken,
    checkCompanyAccess: deps.checkCompanyAccess,
    oauthService: deps.oauthService,
    backupProviderService: deps.backupProviderService,
  });

  registerAdminRoutes(app, {
    pool: deps.pool,
    multer: deps.multer,
    authenticateToken: deps.authenticateToken,
    isSuperAdmin: deps.isSuperAdmin,
    checkCompanyAccess: deps.checkCompanyAccess,
    verifyPassword: deps.verifyPassword,
    logAudit: deps.logAudit,
    backupProviderService: deps.backupProviderService,
    productIdentifierService: deps.productIdentifierService,
    getTable: deps.getTable,
    normalizePassportTypeSchema: deps.normalizePassportTypeSchema,
    getTypeSchemaVersion: deps.getTypeSchemaVersion,
    buildPassportTypeSchemaChange: deps.buildPassportTypeSchemaChange,
    passportTypeHasStoredRecords: deps.passportTypeHasStoredRecords,
    createPassportTable: deps.createPassportTable,
    validatePassportTypeStorage: deps.validatePassportTypeStorage,
    queryTableStats: deps.queryTableStats,
    publicReadRateLimit: deps.publicReadRateLimit,
    GLOBAL_SYMBOLS_DIR: deps.GLOBAL_SYMBOLS_DIR,
    REPO_BASE_DIR: deps.REPO_BASE_DIR,
    FILES_BASE_DIR: deps.FILES_BASE_DIR,
    IN_REVISION_STATUS: deps.IN_REVISION_STATUS,
    IN_REVISION_STATUSES_SQL: deps.IN_REVISION_STATUSES_SQL,
    createTransporter: deps.createTransporter,
    brandedEmail: deps.brandedEmail,
    renderInfoTable: deps.renderInfoTable,
    storageService: deps.storageService,
  });

  registerAssetManagementApiRoutes(app, {
    pool: deps.pool,
    requireAssetManagementKey: deps.requireAssetManagementKey,
    authenticateAssetPlatform: deps.authenticateAssetPlatform,
    requireAssetEditor: deps.requireAssetEditor,
    publicReadRateLimit: deps.publicReadRateLimit,
    assetWriteRateLimit: deps.assetWriteRateLimit,
    assetSourceFetchRateLimit: deps.assetSourceFetchRateLimit,
    ASSET_ERP_PRESETS: deps.ASSET_ERP_PRESETS,
    ASSET_MATCH_FIELDS: deps.ASSET_MATCH_FIELDS,
    IN_REVISION_STATUS: deps.IN_REVISION_STATUS,
    assertAssetManagementEnabled: deps.assertAssetManagementEnabled,
    assertCompanyAssetPassportTypeAccess: deps.assertCompanyAssetPassportTypeAccess,
    getLatestCompanyPassports: deps.getLatestCompanyPassports,
    getAssetFieldMap: deps.getAssetFieldMap,
    isPlainObject: deps.isPlainObject,
    normalizePassportRequestBody: deps.normalizePassportRequestBody,
    fetchAssetSourceRecords: deps.fetchAssetSourceRecords,
    prepareAssetPayload: deps.prepareAssetPayload,
    executeAssetPush: deps.executeAssetPush,
    runAssetManagementJob: deps.runAssetManagementJob,
    recordAssetRun: deps.recordAssetRun,
    resolveAssetJobNextRunAt: deps.resolveAssetJobNextRunAt,
  });

  registerPassportRoutes(app, {
    pool: deps.pool,
    fs: deps.fs,
    crypto: deps.crypto,
    authenticateToken: deps.authenticateToken,
    isSuperAdmin: deps.isSuperAdmin,
    checkCompanyAccess: deps.checkCompanyAccess,
    checkCompanyAdmin: deps.checkCompanyAdmin,
    requireEditor: deps.requireEditor,
    requireDraftEditor: deps.requireDraftEditor,
    authenticateApiKey: deps.authenticateApiKey,
    requireApiKeyScope: deps.requireApiKeyScope,
    publicReadRateLimit: deps.publicReadRateLimit,
    publicHeavyRateLimit: deps.publicHeavyRateLimit,
    apiKeyReadRateLimit: deps.apiKeyReadRateLimit,
    assetWriteRateLimit: deps.assetWriteRateLimit,
    upload: deps.upload,
    hashSecret: deps.hashSecret,
    createAccessKeyMaterial: deps.createAccessKeyMaterial,
    createDeviceKeyMaterial: deps.createDeviceKeyMaterial,
    IN_REVISION_STATUSES_SQL: deps.IN_REVISION_STATUSES_SQL,
    EDITABLE_RELEASE_STATUSES_SQL: deps.EDITABLE_RELEASE_STATUSES_SQL,
    REVISION_BLOCKING_STATUSES_SQL: deps.REVISION_BLOCKING_STATUSES_SQL,
    EDIT_SESSION_TIMEOUT_HOURS: deps.EDIT_SESSION_TIMEOUT_HOURS,
    EDIT_SESSION_TIMEOUT_SQL: deps.EDIT_SESSION_TIMEOUT_SQL,
    IN_REVISION_STATUS: deps.IN_REVISION_STATUS,
    SYSTEM_PASSPORT_FIELDS: deps.SYSTEM_PASSPORT_FIELDS,
    getTable: deps.getTable,
    normalizePassportRow: deps.normalizePassportRow,
    normalizeReleaseStatus: deps.normalizeReleaseStatus,
    isEditablePassportStatus: deps.isEditablePassportStatus,
    normalizeInternalAliasIdValue: deps.normalizeInternalAliasIdValue,
    generateInternalAliasIdValue: deps.generateInternalAliasIdValue,
    normalizePassportRequestBody: deps.normalizePassportRequestBody,
    extractExplicitFacilityId: deps.extractExplicitFacilityId,
    getWritablePassportColumns: deps.getWritablePassportColumns,
    getStoredPassportValues: deps.getStoredPassportValues,
    toStoredPassportValue: deps.toStoredPassportValue,
    coerceBulkFieldValue: deps.coerceBulkFieldValue,
    buildCurrentPublicPassportPath: deps.buildCurrentPublicPassportPath,
    buildInactivePublicPassportPath: deps.buildInactivePublicPassportPath,
    buildPreviewPassportPath: deps.buildPreviewPassportPath,
    isPublicHistoryStatus: deps.isPublicHistoryStatus,
    logAudit: deps.logAudit,
    getPassportTypeSchema: deps.getPassportTypeSchema,
    findExistingPassportByInternalAliasId: deps.findExistingPassportByInternalAliasId,
    getPassportLineageContext: deps.getPassportLineageContext,
    getPassportVersionsByLineage: deps.getPassportVersionsByLineage,
    fetchCompanyPassportRecord: deps.fetchCompanyPassportRecord,
    resolveCompanyPreviewPassport: deps.resolveCompanyPreviewPassport,
    archivePassportSnapshot: deps.archivePassportSnapshot,
    archivePassportSnapshots: deps.archivePassportSnapshots,
    updatePassportRowById: deps.updatePassportRowById,
    buildPassportVersionHistory: deps.buildPassportVersionHistory,
    clearExpiredEditSessions: deps.clearExpiredEditSessions,
    listActiveEditSessions: deps.listActiveEditSessions,
    markOlderVersionsObsolete: deps.markOlderVersionsObsolete,
    verifyAuditLogChain: deps.verifyAuditLogChain,
    buildAuditLogRootSummary: deps.buildAuditLogRootSummary,
    listAuditLogAnchors: deps.listAuditLogAnchors,
    anchorAuditLogRoot: deps.anchorAuditLogRoot,
    stripRestrictedFieldsForPublicView: deps.stripRestrictedFieldsForPublicView,
    getCompanyNameMap: deps.getCompanyNameMap,
    queryTableStats: deps.queryTableStats,
    submitPassportToWorkflow: deps.submitPassportToWorkflow,
    signPassport: deps.signPassport,
    signPortableDataConstruct: deps.signPortableDataConstruct,
    buildBatteryPassJsonExport: deps.buildBatteryPassJsonExport,
    storageService: deps.storageService,
    complianceService: deps.complianceService,
    accessRightsService: deps.accessRightsService,
    productIdentifierService: deps.productIdentifierService,
    backupProviderService: deps.backupProviderService,
    buildExpandedPassportPayload: deps.buildExpandedPassportPayload,
    createPassportTable: deps.createPassportTable,
  });

  registerPassportPublicRoutes(app, {
    pool: deps.pool,
    crypto: deps.crypto,
    publicReadRateLimit: deps.publicReadRateLimit,
    publicHeavyRateLimit: deps.publicHeavyRateLimit,
    publicUnlockRateLimit: deps.publicUnlockRateLimit,
    getTable: deps.getTable,
    normalizePassportRow: deps.normalizePassportRow,
    normalizeInternalAliasIdValue: deps.normalizeInternalAliasIdValue,
    buildCurrentPublicPassportPath: deps.buildCurrentPublicPassportPath,
    buildInactivePublicPassportPath: deps.buildInactivePublicPassportPath,
    stripRestrictedFieldsForPublicView: deps.stripRestrictedFieldsForPublicView,
    getCompanyNameMap: deps.getCompanyNameMap,
    resolveReleasedPassportByInternalAliasId: deps.resolveReleasedPassportByInternalAliasId,
    resolvePublicPassportByDppId: deps.resolvePublicPassportByDppId,
    buildPassportVersionHistory: deps.buildPassportVersionHistory,
    resolvePublicPathToSubjects: deps.resolvePublicPathToSubjects,
    verifyPassportSignature: deps.verifyPassportSignature,
    logAudit: deps.logAudit,
    buildJsonLdContext: deps.buildJsonLdContext,
    buildBatteryPassJsonExport: deps.buildBatteryPassJsonExport,
    buildCanonicalPassportPayload: deps.buildCanonicalPassportPayload,
    buildExpandedPassportPayload: deps.buildExpandedPassportPayload,
    backupProviderService: deps.backupProviderService,
    signingService: deps.signingService,
    didService: deps.didService,
    productIdentifierService: deps.productIdentifierService,
  });

  registerCompanyRoutes(app, {
    pool: deps.pool,
    authenticateToken: deps.authenticateToken,
    checkCompanyAccess: deps.checkCompanyAccess,
    requireEditor: deps.requireEditor,
    publicReadRateLimit: deps.publicReadRateLimit,
    getTable: deps.getTable,
    getPassportFieldValue: deps.getPassportFieldValue,
    getPassportTypeSchema: deps.getPassportTypeSchema,
    normalizePassportRequestBody: deps.normalizePassportRequestBody,
    extractExplicitFacilityId: deps.extractExplicitFacilityId,
    normalizeInternalAliasIdValue: deps.normalizeInternalAliasIdValue,
    normalizeReleaseStatus: deps.normalizeReleaseStatus,
    isEditablePassportStatus: deps.isEditablePassportStatus,
    findExistingPassportByInternalAliasId: deps.findExistingPassportByInternalAliasId,
    updatePassportRowById: deps.updatePassportRowById,
    getWritablePassportColumns: deps.getWritablePassportColumns,
    getStoredPassportValues: deps.getStoredPassportValues,
    logAudit: deps.logAudit,
    EDITABLE_RELEASE_STATUSES_SQL: deps.EDITABLE_RELEASE_STATUSES_SQL,
    SYSTEM_PASSPORT_FIELDS: deps.SYSTEM_PASSPORT_FIELDS,
    buildBatteryPassJsonExport: deps.buildBatteryPassJsonExport,
    buildExpandedPassportPayload: deps.buildExpandedPassportPayload,
    productIdentifierService: deps.productIdentifierService,
    complianceService: deps.complianceService,
    accessRightsService: deps.accessRightsService,
  });

  registerDppApiRoutes(app, {
    pool: deps.pool,
    publicReadRateLimit: deps.publicReadRateLimit,
    authenticateToken: deps.authenticateToken,
    requireEditor: deps.requireEditor,
    getTable: deps.getTable,
    normalizePassportRow: deps.normalizePassportRow,
    normalizeInternalAliasIdValue: deps.normalizeInternalAliasIdValue,
    extractExplicitFacilityId: deps.extractExplicitFacilityId,
    stripRestrictedFieldsForPublicView: deps.stripRestrictedFieldsForPublicView,
    getCompanyNameMap: deps.getCompanyNameMap,
    resolveReleasedPassportByInternalAliasId: deps.resolveReleasedPassportByInternalAliasId,
    signingService: deps.signingService,
    buildOperationalDppPayload: deps.buildOperationalDppPayload,
    buildCanonicalPassportPayload: deps.buildCanonicalPassportPayload,
    buildExpandedPassportPayload: deps.buildExpandedPassportPayload,
    buildExpandedDataElement: deps.buildExpandedDataElement,
    buildPassportJsonLdContext: deps.buildPassportJsonLdContext,
    didService: deps.didService,
    dppIdentity: deps.dppIdentity,
    productIdentifierService: deps.productIdentifierService,
    archivePassportSnapshot: deps.archivePassportSnapshot,
    updatePassportRowById: deps.updatePassportRowById,
    isEditablePassportStatus: deps.isEditablePassportStatus,
    logAudit: deps.logAudit,
    accessRightsService: deps.accessRightsService,
    normalizePassportRequestBody: deps.normalizePassportRequestBody,
    SYSTEM_PASSPORT_FIELDS: deps.SYSTEM_PASSPORT_FIELDS,
    getWritablePassportColumns: deps.getWritablePassportColumns,
    toStoredPassportValue: deps.toStoredPassportValue,
    getPassportTypeSchema: deps.getPassportTypeSchema,
    findExistingPassportByInternalAliasId: deps.findExistingPassportByInternalAliasId,
    complianceService: deps.complianceService,
    backupProviderService: deps.backupProviderService,
  });

  registerDictionaryRoutes(app, {
    publicReadRateLimit: deps.publicReadRateLimit,
    batteryDictionaryService: deps.batteryDictionaryService,
  });

  registerHealthRoutes(app, {
    pool: deps.pool,
    storageService: deps.storageService,
  });
}

module.exports = {
  registerAppRoutes,
};
