"use strict";

const registerRepositoryRoutes = require("../http/routes/repository");
const registerNotificationRoutes = require("../http/routes/notifications");
const registerWorkflowRoutes = require("../http/routes/workflow");
const registerHealthRoutes = require("../http/routes/health");
const registerAuthRoutes = require("../http/routes/auth");
const registerAdminRoutes = require("../http/routes/admin");
const registerAssetManagementApiRoutes = require("../http/routes/asset-management-api");
const registerPassportRoutes = require("../http/routes/passports");
const registerPassportPublicRoutes = require("../http/routes/passport-public");
const registerCompanyRoutes = require("../http/routes/company");
const registerDppApiRoutes = require("../http/routes/dpp-api");
const registerDictionaryRoutes = require("../http/routes/dictionary");

function registerAppRoutes(app, deps) {
  registerRepositoryRoutes(app, {
    pool: deps.pool,
    fs: deps.fs,
    path: deps.path,
    publicReadRateLimit: deps.publicReadRateLimit,
    authenticateToken: deps.authenticateToken,
    checkCompanyAccess: deps.checkCompanyAccess,
    requireEditor: deps.requireEditor,
    repoUpload: deps.repoUpload,
    repoSymbolUpload: deps.repoSymbolUpload,
    validateRepositoryPdfUpload: deps.validateRepositoryPdfUpload,
    validateRepositorySymbolUpload: deps.validateRepositorySymbolUpload,
    repoBaseDir: deps.repoBaseDir,
    isPathInsideBase: deps.isPathInsideBase,
    storageService: deps.storageService,
  });

  registerNotificationRoutes(app, { pool: deps.pool, authenticateToken: deps.authenticateToken });

  registerWorkflowRoutes(app, {
    pool: deps.pool,
    authenticateToken: deps.authenticateToken,
    checkCompanyAccess: deps.checkCompanyAccess,
    requireEditor: deps.requireEditor,
    submitPassportToWorkflow: deps.submitPassportToWorkflow,
    getTable: deps.getTable,
    inRevisionStatus: deps.inRevisionStatus,
    signPassport: deps.signPassport,
    markOlderVersionsObsolete: deps.markOlderVersionsObsolete,
    logAudit: deps.logAudit,
    buildCurrentPublicPassportPath: deps.buildCurrentPublicPassportPath,
    createNotification: deps.createNotification,
    complianceService: deps.complianceService,
    archivePassportSnapshot: deps.archivePassportSnapshot,
    renderInfoTable: deps.renderInfoTable,
  });

  registerAuthRoutes(app, {
    pool: deps.pool,
    jwt: deps.jwt,
    jwtSecret: deps.jwtSecret,
    hashPassword: deps.hashPassword,
    verifyPassword: deps.verifyPassword,
    verifyPasswordAndUpgrade: deps.verifyPasswordAndUpgrade,
    generateToken: deps.generateToken,
    hashOpaqueToken: deps.hashOpaqueToken,
    validatePasswordPolicy: deps.validatePasswordPolicy,
    passwordMinLength: deps.passwordMinLength,
    hashOtpCode: deps.hashOtpCode,
    generateOtpCode: deps.generateOtpCode,
    sessionCookieName: deps.sessionCookieName,
    setAuthCookie: deps.setAuthCookie,
    clearAuthCookie: deps.clearAuthCookie,
    sendOtpEmail: deps.sendOtpEmail,
    createTransporter: deps.createTransporter,
    brandedEmail: deps.brandedEmail,
    renderInfoTable: deps.renderInfoTable,
    logAudit: deps.logAudit,
    authRateLimit: deps.authRateLimit,
    otpRateLimit: deps.otpRateLimit,
    passwordResetRateLimit: deps.passwordResetRateLimit,
    publicReadRateLimit: deps.publicReadRateLimit,
    authenticateToken: deps.authenticateToken,
    checkCompanyAccess: deps.checkCompanyAccess,
    oauthService: deps.oauthService,
    backupProviderService: deps.backupProviderService,
  });

  registerAdminRoutes(app, {
    pool: deps.pool,
    multer: deps.multer,
    authenticateToken: deps.authenticateToken,
    isSuperAdmin: deps.isSuperAdmin,
    verifyPassword: deps.verifyPassword,
    logAudit: deps.logAudit,
    backupProviderService: deps.backupProviderService,
    productIdentifierService: deps.productIdentifierService,
    getTable: deps.getTable,
    normalizePassportTypeSchema: deps.normalizePassportTypeSchema,
    getTypeSchemaVersion: deps.getTypeSchemaVersion,
    buildPassportTypeSchemaChange: deps.buildPassportTypeSchemaChange,
    passportTypeHasStoredRecords: deps.passportTypeHasStoredRecords,
    createPassportTable: deps.createPassportTable,
    validatePassportTypeStorage: deps.validatePassportTypeStorage,
    queryTableStats: deps.queryTableStats,
    globalSymbolsDir: deps.globalSymbolsDir,
    repoBaseDir: deps.repoBaseDir,
    filesBaseDir: deps.filesBaseDir,
    inRevisionStatus: deps.inRevisionStatus,
    inRevisionStatusesSql: deps.inRevisionStatusesSql,
    createTransporter: deps.createTransporter,
    brandedEmail: deps.brandedEmail,
    renderInfoTable: deps.renderInfoTable,
    storageService: deps.storageService,
  });

  registerAssetManagementApiRoutes(app, {
    pool: deps.pool,
    authenticateToken: deps.authenticateToken,
    checkCompanyAccess: deps.checkCompanyAccess,
    requireEditor: deps.requireEditor,
    publicReadRateLimit: deps.publicReadRateLimit,
    assetWriteRateLimit: deps.assetWriteRateLimit,
    assetSourceFetchRateLimit: deps.assetSourceFetchRateLimit,
    assetErpPresets: deps.assetErpPresets,
    assetMatchFields: deps.assetMatchFields,
    inRevisionStatus: deps.inRevisionStatus,
    assertAssetManagementEnabled: deps.assertAssetManagementEnabled,
    assertCompanyAssetPassportTypeAccess: deps.assertCompanyAssetPassportTypeAccess,
    getLatestCompanyPassports: deps.getLatestCompanyPassports,
    getAssetFieldMap: deps.getAssetFieldMap,
    isPlainObject: deps.isPlainObject,
    normalizePassportRequestBody: deps.normalizePassportRequestBody,
    fetchAssetSourceRecords: deps.fetchAssetSourceRecords,
    prepareAssetPayload: deps.prepareAssetPayload,
    executeAssetPush: deps.executeAssetPush,
    runAssetManagementJob: deps.runAssetManagementJob,
    recordAssetRun: deps.recordAssetRun,
    resolveAssetJobNextRunAt: deps.resolveAssetJobNextRunAt,
  });

  registerPassportRoutes(app, {
    pool: deps.pool,
    fs: deps.fs,
    crypto: deps.crypto,
    authenticateToken: deps.authenticateToken,
    requireBearerToken: deps.requireBearerToken,
    isSuperAdmin: deps.isSuperAdmin,
    checkCompanyAccess: deps.checkCompanyAccess,
    checkCompanyAdmin: deps.checkCompanyAdmin,
    requireEditor: deps.requireEditor,
    requireDraftEditor: deps.requireDraftEditor,
    publicReadRateLimit: deps.publicReadRateLimit,
    publicUnlockRateLimit: deps.publicUnlockRateLimit,
    integrationWriteRateLimit: deps.integrationWriteRateLimit,
    assetWriteRateLimit: deps.assetWriteRateLimit,
    upload: deps.upload,
    validatePdfUpload: deps.validatePdfUpload,
    hashSecret: deps.hashSecret,
    createDeviceKeyMaterial: deps.createDeviceKeyMaterial,
    inRevisionStatusesSql: deps.inRevisionStatusesSql,
    editableReleaseStatusesSql: deps.editableReleaseStatusesSql,
    revisionBlockingStatusesSql: deps.revisionBlockingStatusesSql,
    editSessionTimeoutHours: deps.editSessionTimeoutHours,
    editSessionTimeoutSql: deps.editSessionTimeoutSql,
    inRevisionStatus: deps.inRevisionStatus,
    systemPassportFields: deps.systemPassportFields,
    getTable: deps.getTable,
    getPassportFieldValue: deps.getPassportFieldValue,
    normalizePassportRow: deps.normalizePassportRow,
    normalizeReleaseStatus: deps.normalizeReleaseStatus,
    isEditablePassportStatus: deps.isEditablePassportStatus,
    normalizeInternalAliasIdValue: deps.normalizeInternalAliasIdValue,
    generateInternalAliasIdValue: deps.generateInternalAliasIdValue,
    normalizePassportRequestBody: deps.normalizePassportRequestBody,
    extractExplicitFacilityId: deps.extractExplicitFacilityId,
    getWritablePassportColumns: deps.getWritablePassportColumns,
    getStoredPassportValues: deps.getStoredPassportValues,
    quoteSqlIdentifier: deps.quoteSqlIdentifier,
    joinQuotedSqlIdentifiers: deps.joinQuotedSqlIdentifiers,
    toStoredPassportValue: deps.toStoredPassportValue,
    coerceBulkFieldValue: deps.coerceBulkFieldValue,
    buildCurrentPublicPassportPath: deps.buildCurrentPublicPassportPath,
    buildInactivePublicPassportPath: deps.buildInactivePublicPassportPath,
    buildPreviewPassportPath: deps.buildPreviewPassportPath,
    isPublicHistoryStatus: deps.isPublicHistoryStatus,
    logAudit: deps.logAudit,
    getPassportTypeSchema: deps.getPassportTypeSchema,
    findExistingPassportByInternalAliasId: deps.findExistingPassportByInternalAliasId,
    getPassportLineageContext: deps.getPassportLineageContext,
    getPassportVersionsByLineage: deps.getPassportVersionsByLineage,
    fetchCompanyPassportRecord: deps.fetchCompanyPassportRecord,
    resolveCompanyPreviewPassport: deps.resolveCompanyPreviewPassport,
    archivePassportSnapshot: deps.archivePassportSnapshot,
    archivePassportSnapshots: deps.archivePassportSnapshots,
    updatePassportRowById: deps.updatePassportRowById,
    buildPassportVersionHistory: deps.buildPassportVersionHistory,
    clearExpiredEditSessions: deps.clearExpiredEditSessions,
    listActiveEditSessions: deps.listActiveEditSessions,
    markOlderVersionsObsolete: deps.markOlderVersionsObsolete,
    verifyAuditLogChain: deps.verifyAuditLogChain,
    buildAuditLogRootSummary: deps.buildAuditLogRootSummary,
    listAuditLogAnchors: deps.listAuditLogAnchors,
    anchorAuditLogRoot: deps.anchorAuditLogRoot,
    stripRestrictedFieldsForPublicView: deps.stripRestrictedFieldsForPublicView,
    getCompanyNameMap: deps.getCompanyNameMap,
    queryTableStats: deps.queryTableStats,
    submitPassportToWorkflow: deps.submitPassportToWorkflow,
    signPassport: deps.signPassport,
    signPortableDataConstruct: deps.signPortableDataConstruct,
    buildSemanticPassportJsonExport: deps.buildSemanticPassportJsonExport,
    buildCanonicalPassportPayload: deps.buildCanonicalPassportPayload,
    storageService: deps.storageService,
    complianceService: deps.complianceService,
    didService: deps.didService,
    productIdentifierService: deps.productIdentifierService,
    backupProviderService: deps.backupProviderService,
    buildExpandedPassportPayload: deps.buildExpandedPassportPayload,
    createPassportTable: deps.createPassportTable,
  });

  registerPassportPublicRoutes(app, {
    pool: deps.pool,
    crypto: deps.crypto,
    publicReadRateLimit: deps.publicReadRateLimit,
    publicUnlockRateLimit: deps.publicUnlockRateLimit,
    getTable: deps.getTable,
    normalizePassportRow: deps.normalizePassportRow,
    buildCurrentPublicPassportPath: deps.buildCurrentPublicPassportPath,
    buildInactivePublicPassportPath: deps.buildInactivePublicPassportPath,
    stripRestrictedFieldsForPublicView: deps.stripRestrictedFieldsForPublicView,
    getCompanyNameMap: deps.getCompanyNameMap,
    resolvePublicPassportByDppId: deps.resolvePublicPassportByDppId,
    buildPassportVersionHistory: deps.buildPassportVersionHistory,
    verifyPassportSignature: deps.verifyPassportSignature,
    logAudit: deps.logAudit,
    buildSemanticPassportJsonExport: deps.buildSemanticPassportJsonExport,
    buildCanonicalPassportPayload: deps.buildCanonicalPassportPayload,
    buildExpandedPassportPayload: deps.buildExpandedPassportPayload,
    backupProviderService: deps.backupProviderService,
    signingService: deps.signingService,
    didService: deps.didService,
    productIdentifierService: deps.productIdentifierService,
  });

  registerCompanyRoutes(app, {
    pool: deps.pool,
    authenticateToken: deps.authenticateToken,
    checkCompanyAccess: deps.checkCompanyAccess,
    requireEditor: deps.requireEditor,
    publicReadRateLimit: deps.publicReadRateLimit,
    getTable: deps.getTable,
    getPassportFieldValue: deps.getPassportFieldValue,
    getPassportTypeSchema: deps.getPassportTypeSchema,
    normalizePassportRequestBody: deps.normalizePassportRequestBody,
    extractExplicitFacilityId: deps.extractExplicitFacilityId,
    normalizeInternalAliasIdValue: deps.normalizeInternalAliasIdValue,
    normalizeReleaseStatus: deps.normalizeReleaseStatus,
    isEditablePassportStatus: deps.isEditablePassportStatus,
    findExistingPassportByInternalAliasId: deps.findExistingPassportByInternalAliasId,
    updatePassportRowById: deps.updatePassportRowById,
    getWritablePassportColumns: deps.getWritablePassportColumns,
    getStoredPassportValues: deps.getStoredPassportValues,
    logAudit: deps.logAudit,
    editableReleaseStatusesSql: deps.editableReleaseStatusesSql,
    systemPassportFields: deps.systemPassportFields,
    buildSemanticPassportJsonExport: deps.buildSemanticPassportJsonExport,
    buildExpandedPassportPayload: deps.buildExpandedPassportPayload,
    productIdentifierService: deps.productIdentifierService,
    complianceService: deps.complianceService,
  });

  registerDppApiRoutes(app, {
    pool: deps.pool,
    authenticateToken: deps.authenticateToken,
    requireBearerToken: deps.requireBearerToken,
    integrationWriteRateLimit: deps.integrationWriteRateLimit,
    requireEditor: deps.requireEditor,
    getTable: deps.getTable,
    normalizePassportRow: deps.normalizePassportRow,
    normalizeInternalAliasIdValue: deps.normalizeInternalAliasIdValue,
    extractExplicitFacilityId: deps.extractExplicitFacilityId,
    getCompanyNameMap: deps.getCompanyNameMap,
    buildCanonicalPassportPayload: deps.buildCanonicalPassportPayload,
    buildExpandedPassportPayload: deps.buildExpandedPassportPayload,
    didService: deps.didService,
    productIdentifierService: deps.productIdentifierService,
    archivePassportSnapshot: deps.archivePassportSnapshot,
    updatePassportRowById: deps.updatePassportRowById,
    isEditablePassportStatus: deps.isEditablePassportStatus,
    logAudit: deps.logAudit,
    normalizePassportRequestBody: deps.normalizePassportRequestBody,
    systemPassportFields: deps.systemPassportFields,
    getWritablePassportColumns: deps.getWritablePassportColumns,
    joinQuotedSqlIdentifiers: deps.joinQuotedSqlIdentifiers,
    toStoredPassportValue: deps.toStoredPassportValue,
    getPassportTypeSchema: deps.getPassportTypeSchema,
    findExistingPassportByInternalAliasId: deps.findExistingPassportByInternalAliasId,
    complianceService: deps.complianceService,
    backupProviderService: deps.backupProviderService,
  });

  registerDictionaryRoutes(app, {
    pool: deps.pool,
    publicReadRateLimit: deps.publicReadRateLimit,
    authenticateToken: deps.authenticateToken,
    checkCompanyAccess: deps.checkCompanyAccess,
    semanticModelRegistry: deps.semanticModelRegistry,
  });

  registerHealthRoutes(app, {
    pool: deps.pool,
    storageService: deps.storageService,
  });
}

module.exports = {
  registerAppRoutes,
};
