import React, { useState, useEffect, useRef } from "react";
import { useNavigate, useParams, useLocation } from "react-router-dom";
import { PASSPORT_SECTIONS_MAP } from "../config/PassportFields";
import { authHeaders, fetchWithAuth } from "../../shared/api/authHeaders";
import {
  HEADER_OWNERSHIP_LABELS,
  normalizeSystemPassportHeader,
} from "../../admin/passport-types/builderHelpers";
import RepositoryPicker from "./components/RepositoryPicker";
import "../../assets/styles/CreatePass.css";

const API = import.meta.env.VITE_API_URL || "";
const EDIT_SESSION_TIMEOUT_MS = 12 * 60 * 60 * 1000;
const EDIT_HEARTBEAT_MS = 60 * 1000;
const HEADER_SOURCE_LABELS = {
  system: "Generated by system",
  company_policy: "From company policy",
  passport_type: "From passport type",
  company_identity: "From company identity",
  company_or_passport: "From company or passport",
};

function PassportForm({ token, user, companyId, mode = "create", passportType: typeProp }) {
  const navigate  = useNavigate();
  const location  = useLocation();
  const { dppId, passportType: typeParam } = useParams();

  const passportType = typeProp || typeParam ||
    new URLSearchParams(location.search).get("passportType");
  const templateId = new URLSearchParams(location.search).get("templateId");
  const effectiveCompanyId = String(
    companyId ||
    user?.companyId ||
    user?.company_id ||
    localStorage.getItem("companyId") ||
    ""
  );

  // Support both static PASSPORT_SECTIONS_MAP and dynamic type definitions from DB
  const [dynamicSections, setDynamicSections] = useState(null);
  const [loadingType,     setLoadingType]     = useState(false);
  const [systemHeader,    setSystemHeader]    = useState(() => normalizeSystemPassportHeader());
  const [complianceContext, setComplianceContext] = useState({ company: null, facilities: [] });

  const SECTIONS    = dynamicSections || PASSPORT_SECTIONS_MAP[passportType] || {};
  const sectionKeys = Object.keys(SECTIONS);

  const [expanded,       setExpanded]       = useState({});
  const [modelName,      setModelName]      = useState("");
  const [productId,      setProductId]      = useState("");
  const [formData,       setFormData]       = useState({});
  const [modelDataKeys,  setModelDataKeys]  = useState(new Set()); // fields locked from template
  const [templateName,   setTemplateName]   = useState("");
  const [fileSelections, setFileSelections] = useState({});
  const [uploadProgress, setUploadProgress] = useState({});
  const [repoPicker,     setRepoPicker]     = useState(null);  // field.key being picked, or null
  const [symbolPicker,   setSymbolPicker]   = useState(null);  // field.key being picked, or null
  const [symbols,        setSymbols]        = useState([]);
  const [isLoading,      setIsLoading]      = useState(mode === "edit");
  const [isSaving,       setIsSaving]       = useState(false);
  const [error,          setError]          = useState("");
  const [success,        setSuccess]        = useState("");
  const [displayName,    setDisplayName]    = useState("");
  const [activeEditors,  setActiveEditors]  = useState([]);
  const [autoSaveState,  setAutoSaveState]  = useState("idle");
  const [sessionExpired, setSessionExpired] = useState(false);
  const [lastSavedAt,    setLastSavedAt]    = useState(null);

  const lastInteractionRef = useRef(Date.now());
  const dirtyRef           = useRef(false);
  const saveInFlightRef    = useRef(false);
  const sessionActiveRef   = useRef(false);
  const mountedRef         = useRef(true);

  const markDirty = () => {
    dirtyRef.current = true;
    if (mode === "edit") setAutoSaveState("pending");
  };

  useEffect(() => {
    return () => {
      mountedRef.current = false;
    };
  }, []);

  // Load symbols from company repository
  useEffect(() => {
    if (!effectiveCompanyId) return;
    fetchWithAuth(`${API}/api/companies/${effectiveCompanyId}/repository/symbols`, { headers: authHeaders() })
      .then(r => r.ok ? r.json() : [])
      .then(setSymbols)
      .catch(() => {});
  }, [effectiveCompanyId]);

  useEffect(() => {
    if (!effectiveCompanyId) return;
    fetchWithAuth(`${API}/api/companies/${effectiveCompanyId}/compliance-identity`, { headers: authHeaders() })
      .then((r) => r.ok ? r.json() : null)
      .then((data) => {
        if (!data) return;
        const activeFacilities = Array.isArray(data.facilities)
          ? data.facilities.filter((facility) => facility?.is_active)
          : [];
        setComplianceContext({
          company: data.company || null,
          facilities: activeFacilities,
        });
        setFormData((prev) => {
          const next = { ...prev };
          if (!next.economic_operator_id && data.company?.economic_operator_identifier) {
            next.economic_operator_id = data.company.economic_operator_identifier;
          }
          if (!next.economic_operator_identifier_scheme && data.company?.economic_operator_identifier_scheme) {
            next.economic_operator_identifier_scheme = data.company.economic_operator_identifier_scheme;
          }
          if (!next.facility_id && activeFacilities.length === 1) {
            next.facility_id = activeFacilities[0].facility_identifier;
          }
          return next;
        });
      })
      .catch(() => {});
  }, [effectiveCompanyId]);

  // Load dynamic type definition from server if not in static map
  useEffect(() => {
    if (!passportType) return;
    if (PASSPORT_SECTIONS_MAP[passportType]) {
      setDynamicSections(null); // Use static map
      setSystemHeader(normalizeSystemPassportHeader());
      return;
    }
    // Try fetching from server
    setLoadingType(true);
    fetchWithAuth(`${API}/api/passport-types/${passportType}`)
      .then(r => r.ok ? r.json() : null)
      .then(data => {
        if (data?.fields_json?.sections) {
          // Convert server format to component format
          const sections = {};
          for (const section of data.fields_json.sections) {
            sections[section.key] = {
              label: section.label,
              fields: section.fields || [],
            };
          }
          setDynamicSections(sections);
          setSystemHeader(normalizeSystemPassportHeader(data.fields_json.systemHeader));
          setDisplayName(data.display_name || passportType);
          // Expand first section by default
          if (data.fields_json.sections.length > 0) {
            setExpanded({ [data.fields_json.sections[0].key]: true });
          }
        }
      })
      .catch(() => {})
      .finally(() => setLoadingType(false));
  }, [passportType]);

  // Set first section expanded by default when sections load
  useEffect(() => {
    if (sectionKeys.length > 0 && Object.keys(expanded).length === 0) {
      setExpanded({ [sectionKeys[0]]: true });
    }
  }, [sectionKeys.join(",")]);

  // Load template pre-fill on create mode
  useEffect(() => {
    if (mode !== "create" || !templateId || !effectiveCompanyId) return;
    fetchWithAuth(`${API}/api/companies/${effectiveCompanyId}/templates/${templateId}`, { headers: authHeaders() })
      .then(r => r.ok ? r.json() : null)
      .then(tmpl => {
        if (!tmpl) return;
        setTemplateName(tmpl.name || "");
        const vals = {};
        const modelKeys = new Set();
        for (const f of tmpl.fields || []) {
          if (f.field_value) vals[f.field_key] = f.field_value;
          if (f.is_model_data) modelKeys.add(f.field_key);
        }
        setFormData(vals);
        setModelDataKeys(modelKeys);
      })
      .catch(() => {});
  }, [mode, templateId, effectiveCompanyId]);

  useEffect(() => {
    if (mode !== "edit" || !dppId || !passportType) return;
    (async () => {
      try {
        const r = await fetchWithAuth(
          `${API}/api/companies/${effectiveCompanyId}/passports/${dppId}?passportType=${passportType}`,
          { headers: authHeaders() }
        );
        if (!r.ok) throw new Error("Failed to load passport");
        const data = await r.json();
        setModelName(data.model_name || "");
        setProductId(data.product_id || "");
        setFormData(data);
        dirtyRef.current = false;
        setLastSavedAt(data.updated_at || null);
      } catch (e) { setError(e.message); }
      finally { setIsLoading(false); }
    })();
  }, [dppId, mode, passportType, effectiveCompanyId, token]);

  const toggle      = (k)        => setExpanded(p => ({ ...p, [k]: !p[k] }));
  const handleField = (key, val) => {
    markDirty();
    setFormData(p => ({ ...p, [key]: val }));
  };

  const handleFile = (key, file) => {
    if (!file) return;
    if (file.type !== "application/pdf") { setError("Only PDF files allowed."); return; }
    if (file.size > 20 * 1024 * 1024)   { setError("Max file size is 20 MB."); return; }
    setError("");
    markDirty();
    setFileSelections(p => ({ ...p, [key]: file }));
  };

  const uploadFile = async (key, file, guidToUse) => {
    const fd = new FormData();
    fd.append("file", file); fd.append("fieldKey", key); fd.append("passportType", passportType);
    setUploadProgress(p => ({ ...p, [key]: "uploading" }));
    const r = await fetchWithAuth(
      `${API}/api/companies/${effectiveCompanyId}/passports/${guidToUse}/upload`,
      { method:"POST", headers: authHeaders(), body:fd }
    );
    if (!r.ok) throw new Error("Upload failed");
    const { url } = await r.json();
    setUploadProgress(p => ({ ...p, [key]: "done" }));
    return url;
  };

  const buildEditableBody = () => {
    const schemaFieldKeys = new Set(
      Object.values(SECTIONS || {})
        .flatMap((section) => Array.isArray(section?.fields) ? section.fields : [])
        .map((field) => field?.key)
        .filter(Boolean)
    );
    const managedEditableKeys = new Set([
      "economic_operator_id",
      "economic_operator_identifier_scheme",
      "facility_id",
      "granularity",
    ]);
    const allowedKeys = new Set([...schemaFieldKeys, ...managedEditableKeys]);
    const cleanData = Object.fromEntries(
      Object.entries(formData)
        .filter(([key]) => allowedKeys.has(key))
        .map(([key, value]) => {
          const normalizedValue = typeof value === "string"
            ? value.trim()
            : value;
          return [key, Array.isArray(normalizedValue) ? JSON.stringify(normalizedValue) : normalizedValue];
        })
    );
    return {
      passportType,
      model_name: modelName.trim() || null,
      product_id: productId.trim() || null,
      ...cleanData,
    };
  };

  const refreshEditPresence = async (method = "GET") => {
    if (mode !== "edit" || !dppId || !passportType || !effectiveCompanyId) return;
    const init = method === "POST"
      ? {
          method,
          headers: authHeaders({ "Content-Type": "application/json" }),
          body: JSON.stringify({ passportType }),
        }
      : {
          method,
          headers: authHeaders(),
        };
    const r = await fetchWithAuth(`${API}/api/companies/${effectiveCompanyId}/passports/${dppId}/edit-session`, init);
    if (!r.ok) throw new Error("Failed to update edit presence");
    const data = await r.json();
    if (mountedRef.current) {
      setActiveEditors(Array.isArray(data.editors) ? data.editors : []);
    }
    sessionActiveRef.current = method === "DELETE" ? false : true;
    return data;
  };

  const releaseEditPresence = async () => {
    if (mode !== "edit" || !dppId || !effectiveCompanyId || !sessionActiveRef.current) return;
    try {
      await fetchWithAuth(`${API}/api/companies/${effectiveCompanyId}/passports/${dppId}/edit-session`, {
        method: "DELETE",
        headers: authHeaders(),
      });
    } catch {}
    sessionActiveRef.current = false;
  };

  const saveEditChanges = async ({ showSuccessMessage = false } = {}) => {
    if (mode !== "edit" || !dppId || !passportType || saveInFlightRef.current) return false;

    saveInFlightRef.current = true;
      if (mountedRef.current) setAutoSaveState("saving");

    try {
      const body = buildEditableBody();
      const r = await fetchWithAuth(`${API}/api/companies/${effectiveCompanyId}/passports/${dppId}`, {
        method:"PATCH",
        headers: authHeaders({ "Content-Type":"application/json" }),
        body: JSON.stringify(body),
      });
      if (!r.ok) {
        const d = await r.json().catch(() => ({}));
        const fieldSuffix = Array.isArray(d.fields) && d.fields.length
          ? ` (${d.fields.join(", ")})`
          : "";
        throw new Error(d.detail || (d.error ? `${d.error}${fieldSuffix}` : "Failed to update"));
      }

      const uploadedKeys = [];
      for (const [key, file] of Object.entries(fileSelections)) {
        if (file) {
          await uploadFile(key, file, dppId);
          uploadedKeys.push(key);
        }
      }
      if (uploadedKeys.length) {
        setFileSelections(prev => {
          const next = { ...prev };
          uploadedKeys.forEach((key) => delete next[key]);
          return next;
        });
      }

      dirtyRef.current = false;
      const nowIso = new Date().toISOString();
      if (mountedRef.current) {
        setLastSavedAt(nowIso);
        setAutoSaveState("saved");
        if (showSuccessMessage) {
          setSuccess("Changes saved successfully");
        }
      }
      return true;
    } catch (e) {
      if (mountedRef.current) {
        setError(e.message);
        setAutoSaveState("error");
      }
      return false;
    } finally {
      saveInFlightRef.current = false;
    }
  };

  useEffect(() => {
    if (mode !== "edit" || !dppId || !passportType || !effectiveCompanyId || isLoading) return;

    refreshEditPresence("POST").catch(() => {});

    const handleActivity = () => {
      lastInteractionRef.current = Date.now();
      if (sessionExpired) {
        setSessionExpired(false);
        refreshEditPresence("POST").catch(() => {});
      }
    };

    const heartbeat = setInterval(async () => {
      const inactiveFor = Date.now() - lastInteractionRef.current;
      if (inactiveFor >= EDIT_SESSION_TIMEOUT_MS) {
        await releaseEditPresence();
        if (mountedRef.current) {
          setSessionExpired(true);
          setActiveEditors([]);
          setSuccess(
            dirtyRef.current
              ? "✓ Edit session ended after 12 hours of inactivity. Unsaved changes are still on this page until you save them."
              : "✓ Edit session ended after 12 hours of inactivity."
          );
        }
        return;
      }
      refreshEditPresence("POST").catch(() => {});
    }, EDIT_HEARTBEAT_MS);

    window.addEventListener("pointerdown", handleActivity);
    window.addEventListener("keydown", handleActivity);
    window.addEventListener("scroll", handleActivity, { passive: true });

    return () => {
      clearInterval(heartbeat);
      window.removeEventListener("pointerdown", handleActivity);
      window.removeEventListener("keydown", handleActivity);
      window.removeEventListener("scroll", handleActivity);
      releaseEditPresence();
    };
  }, [mode, dppId, passportType, effectiveCompanyId, isLoading, sessionExpired]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError(""); setSuccess(""); setIsSaving(true);

    try {
      if (!effectiveCompanyId) {
        throw new Error("No company is attached to this session. Refresh the page and sign in again if needed.");
      }
      let passportDppId = dppId;
      const trimmedProductId = productId.trim();

      if (mode === "create") {
        if (!trimmedProductId) {
          throw new Error("Serial Number is required");
        }
        const serializedData = Object.fromEntries(
          Object.entries(formData).map(([k, v]) => [k, Array.isArray(v) ? JSON.stringify(v) : v])
        );
        const body = {
          passport_type: passportType,
          model_name: modelName.trim() || null,
          product_id: trimmedProductId,
          ...serializedData,
        };
        const r = await fetchWithAuth(`${API}/api/companies/${effectiveCompanyId}/passports`, {
          method:"POST", headers:authHeaders({"Content-Type":"application/json"}),
          body: JSON.stringify(body),
        });
        if (!r.ok) { const d = await r.json(); throw new Error(d.detail || d.error || "Failed to create"); }
        const { passport } = await r.json();
        passportDppId = passport.dppId;
      } else {
        const saved = await saveEditChanges({ showSuccessMessage: false });
        if (!saved) throw new Error("Failed to update");
      }

      if (mode === "create") {
        for (const [key, file] of Object.entries(fileSelections)) {
          if (file) await uploadFile(key, file, passportDppId);
        }
        setFileSelections({});
        window.scrollTo({ top: 0, behavior: "smooth" });
        setSuccess("Passport created successfully");
        setTimeout(() => setSuccess(""), 4000);
        setModelName("");
        setProductId("");
        setFormData({});
      } else {
        window.scrollTo({ top: 0, behavior: "smooth" });
        setSuccess("Changes saved successfully");
        setTimeout(() => setSuccess(""), 4000);
      }
    } catch (e) {
      setError(e.message);
    } finally { setIsSaving(false); }
  };

  const renderField = (field) => {
    const val      = formData[field.key] ?? "";
    const isLocked = mode === "create" && modelDataKeys.has(field.key);
    const disabled = isSaving || (mode==="edit" && isLoading) || isLocked;

    if (field.type === "boolean") {
      return (
        <label style={{ display:"flex", alignItems:"center", gap:8, cursor:"pointer" }}>
          <input type="checkbox" checked={!!val}
            onChange={e => handleField(field.key, e.target.checked)} disabled={disabled} />
          <span style={{ fontSize:14, color:"var(--text-primary)", fontFamily:"var(--font)" }}>{field.label}</span>
        </label>
      );
    }

    if (field.type === "file") {
      const linkedUrl  = typeof val === "string" && val.startsWith("http") ? val : null;
      const fileName   = linkedUrl ? linkedUrl.split("/").pop() : null;
      return (
        <div className="file-upload-widget">
          {linkedUrl ? (
            <div className="file-existing">
              <a href={linkedUrl} target="_blank" rel="noopener noreferrer" className="file-existing-link">
                📄 {decodeURIComponent(fileName || "Document")}
              </a>
              <button type="button" className="file-clear-btn" disabled={disabled}
                onClick={() => handleField(field.key, "")}>✕ Remove</button>
            </div>
          ) : (
            <button type="button" className="file-upload-label" disabled={disabled}
              onClick={() => setRepoPicker(field.key)}>
              <span className="file-placeholder">📁 Link PDF from Repository</span>
            </button>
          )}
          {linkedUrl && (
            <button type="button" className="file-upload-label file-replace-label" disabled={disabled}
              onClick={() => setRepoPicker(field.key)}>
              <span className="file-placeholder">↺ Change</span>
            </button>
          )}
          <div className="file-link-paste">
            <input
              type="text"
              className="file-link-input"
              placeholder="Or paste a repository link here…"
              disabled={disabled}
              value={linkedUrl && document.activeElement?.dataset?.fieldKey !== field.key ? "" : undefined}
              data-field-key={field.key}
              onPaste={(e) => {
                const text = e.clipboardData.getData("text").trim();
                if (text.startsWith("http")) { e.preventDefault(); handleField(field.key, text); }
              }}
              onBlur={(e) => {
                const text = e.target.value.trim();
                if (text.startsWith("http")) { handleField(field.key, text); e.target.value = ""; }
              }}
              onKeyDown={(e) => {
                if (e.key === "Enter") {
                  const text = e.target.value.trim();
                  if (text.startsWith("http")) { handleField(field.key, text); e.target.value = ""; }
                }
              }}
            />
          </div>
        </div>
      );
    }

    if (field.type === "symbol") {
      const linkedUrl = typeof val === "string" && val.startsWith("http") ? val : null;
      const picked    = linkedUrl ? symbols.find(s => s.file_url === linkedUrl) : null;
      return (
        <div className="file-upload-widget">
          {linkedUrl ? (
            <div className="file-existing">
              <img src={linkedUrl} alt={picked?.name || "symbol"} className="pf-symbol-thumb" />
              <span className="file-existing-link">{picked?.name || "Symbol"}</span>
              <button type="button" className="file-clear-btn" disabled={disabled}
                onClick={() => handleField(field.key, "")}>✕ Remove</button>
            </div>
          ) : (
            <button type="button" className="file-upload-label" disabled={disabled}
              onClick={() => setSymbolPicker(field.key)}>
              <span className="file-placeholder">🔣 Link Symbol from Repository</span>
            </button>
          )}
          {linkedUrl && (
            <button type="button" className="file-upload-label file-replace-label" disabled={disabled}
              onClick={() => setSymbolPicker(field.key)}>
              <span className="file-placeholder">↺ Change</span>
            </button>
          )}
          <div className="file-link-paste">
            <input
              type="text"
              className="file-link-input"
              placeholder="Or paste a repository link here…"
              disabled={disabled}
              data-field-key={field.key}
              onPaste={(e) => {
                const text = e.clipboardData.getData("text").trim();
                if (text.startsWith("http")) { e.preventDefault(); handleField(field.key, text); }
              }}
              onBlur={(e) => {
                const text = e.target.value.trim();
                if (text.startsWith("http")) { handleField(field.key, text); e.target.value = ""; }
              }}
              onKeyDown={(e) => {
                if (e.key === "Enter") {
                  const text = e.target.value.trim();
                  if (text.startsWith("http")) { handleField(field.key, text); e.target.value = ""; }
                }
              }}
            />
          </div>
        </div>
      );
    }

    if (field.type === "table") {
      const cols     = field.table_cols || 2;
      const fallbackColumns = field.table_columns?.length
        ? field.table_columns
        : Array.from({ length: cols }, (_, i) => `Column ${i + 1}`);
      let parsed = val;
      if (typeof val === "string" && (val.startsWith("[") || val.startsWith("{"))) {
        try { parsed = JSON.parse(val); } catch { parsed = null; }
      }
      const parsedColumns = Array.isArray(parsed?.columns) && parsed.columns.length
        ? parsed.columns.map((name, index) => String(name || "").trim() || `Column ${index + 1}`)
        : fallbackColumns;
      const defaultRows = Array.isArray(field.table_default_rows) && field.table_default_rows.length
        ? field.table_default_rows.map(r => Array.from({ length: cols }, (_, i) => r[i] ?? ""))
        : [Array(cols).fill("")];
      const parsedRowsSource = Array.isArray(parsed?.rows) ? parsed.rows : (Array.isArray(parsed) ? parsed : null);
      const normalizedRowLength = parsedColumns.length || cols;
      const rows = Array.isArray(parsedRowsSource) && parsedRowsSource.length
        ? parsedRowsSource.map((row) => Array.from({ length: normalizedRowLength }, (_, i) => Array.isArray(row) ? (row[i] ?? "") : ""))
        : defaultRows.map((row) => Array.from({ length: normalizedRowLength }, (_, i) => row[i] ?? ""));

      const commitTable = (nextColumns, nextRows) => {
        handleField(field.key, {
          columns: nextColumns,
          rows: nextRows,
        });
      };

      const updateCell = (ri, ci, v) => {
        const next = rows.map(r => [...r]);
        next[ri][ci] = v;
        commitTable(parsedColumns, next);
      };
      const updateColumnName = (ci, value) => {
        const nextColumns = parsedColumns.map((name, index) => index === ci ? value : name);
        commitTable(nextColumns, rows);
      };
      const addRow = () => commitTable(parsedColumns, [...rows, Array(parsedColumns.length).fill("")]);
      const removeRow = (ri) => {
        const next = rows.filter((_, i) => i !== ri);
        commitTable(parsedColumns, next.length ? next : [Array(parsedColumns.length).fill("")]);
      };
      const addColumn = () => {
        const nextColumns = [...parsedColumns, `Column ${parsedColumns.length + 1}`];
        const nextRows = rows.map((row) => [...row, ""]);
        commitTable(nextColumns, nextRows);
      };
      const removeColumn = (ci) => {
        if (parsedColumns.length <= 1) return;
        const nextColumns = parsedColumns.filter((_, index) => index !== ci);
        const nextRows = rows.map((row) => row.filter((_, index) => index !== ci));
        commitTable(nextColumns, nextRows);
      };

      return (
        <div className="pf-table-wrap">
          <div className="pf-table-toolbar">
            <button type="button" className="pf-table-add-col" onClick={addColumn} disabled={disabled}>+ Add Column</button>
          </div>
          <table className="pf-table">
            <thead>
              <tr>
                {parsedColumns.map((name, ci) => (
                  <th key={ci}>
                    <div className="pf-table-head-cell">
                      <input
                        type="text"
                        value={name}
                        disabled={disabled}
                        onChange={(e) => updateColumnName(ci, e.target.value)}
                        className="pf-table-head-input"
                        placeholder={`Column ${ci + 1}`}
                      />
                      <button
                        type="button"
                        className="pf-table-remove-col"
                        onClick={() => removeColumn(ci)}
                        disabled={disabled || parsedColumns.length <= 1}
                        title="Remove column"
                      >
                        ✕
                      </button>
                    </div>
                  </th>
                ))}
                <th className="pf-table-action-col" />
              </tr>
            </thead>
            <tbody>
              {rows.map((row, ri) => (
                <tr key={ri}>
                  {Array(parsedColumns.length).fill(null).map((_, ci) => (
                    <td key={ci}>
                      <input
                        type="text"
                        value={row[ci] ?? ""}
                        disabled={disabled}
                        placeholder="—"
                        onChange={e => updateCell(ri, ci, e.target.value)}
                        className="pf-table-cell-input"
                      />
                    </td>
                  ))}
                  <td className="pf-table-action-col">
                    <button type="button" className="pf-table-remove-row" onClick={() => removeRow(ri)} disabled={disabled} title="Remove row">✕</button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
          <button type="button" className="pf-table-add-row" onClick={addRow} disabled={disabled}>+ Add Row</button>
        </div>
      );
    }

    if (field.type === "textarea") {
      return <textarea value={val} disabled={disabled}
        placeholder={`Enter ${field.label.toLowerCase()}`}
        onChange={e => handleField(field.key,e.target.value)} />;
    }

    if (field.type === "date") {
      // Store as YYYY-MM-DD (native date format); convert DD/MM/YYYY on load
      const toInput = (v) => {
        if (!v) return "";
        if (/^\d{4}-\d{2}-\d{2}$/.test(v)) return v;
        const [d, m, y] = v.split("/");
        return d && m && y ? `${y}-${m.padStart(2,"0")}-${d.padStart(2,"0")}` : "";
      };
      const fromInput = (v) => v; // keep YYYY-MM-DD internally
      return (
        <div className="pf-date-wrap">
          <input
            type="date"
            value={toInput(val)}
            disabled={disabled}
            onChange={e => handleField(field.key, fromInput(e.target.value))}
            className="pf-date-input"
          />
          <span className="pf-date-hint">DD/MM/YYYY</span>
        </div>
      );
    }

    return <input type="text" value={val} disabled={disabled}
      placeholder={`Enter ${field.label.toLowerCase()}`}
      onChange={e => handleField(field.key,e.target.value)} />;
  };

  const getHeaderDisplayValue = (field) => {
    const releaseStatus = formData.release_status || (mode === "create" ? "draft" : "");
    const values = {
      digitalProductPassportId: formData.dppId || formData.dpp_id || (mode === "create" ? "Generated when passport is saved" : ""),
      uniqueProductIdentifier: productId || formData.product_id || "Uses Serial Number",
      localProductId: productId || formData.product_id || "Uses Serial Number",
      granularity: formData.granularity || "Resolved from company DPP policy",
      dppSchemaVersion: formData.dpp_schema_version || formData.schema_version || "Resolved from passport type",
      dppStatus: releaseStatus,
      lastUpdate: formData.updated_at || (mode === "create" ? "Generated when passport is saved" : ""),
      economicOperatorId: formData.economic_operator_id || user?.economicOperatorId || user?.economic_operator_identifier || "Resolved from company identity",
      facilityId: formData.facility_id || "Optional; resolved from company or passport data",
      contentSpecificationIds: formData.content_specification_ids || "Resolved from passport type compliance profile",
      subjectDid: formData.subject_did || "Generated from product identity",
      dppDid: formData.dpp_did || "Generated from passport identity",
      companyDid: formData.company_did || "Generated from company identity",
    };
    return values[field.key] || "Managed by system";
  };

  const renderPassportHeaderSection = () => {
    const section = systemHeader?.section || {};
    const fields = Array.isArray(systemHeader?.fields) ? systemHeader.fields : [];
    if (!fields.length) return null;

    return (
      <div className="form-section passport-header-section">
        <div className="section-header passport-header-static">
          <span className="section-title">{section.label || "Passport Header"}</span>
          <span className="pf-header-locked-pill">Standards header</span>
        </div>
        <div className="section-content">
          <p className="section-hint">
            These JSON-LD header fields are mandatory for compliant passports. Locked values are generated or resolved by the platform so they cannot be missed during editing.
          </p>
          <div className="pf-header-grid">
            {fields.map((field) => (
              <div key={field.key} className="pf-header-field-card">
                <div className="pf-header-field-top">
                  <div>
                    <label>{field.label}</label>
                    <code>{field.key}</code>
                  </div>
                  <span className={`pf-header-owner pf-header-owner-${field.ownership || "system_generated"}`}>
                    {HEADER_OWNERSHIP_LABELS[field.ownership] || field.ownership || "System generated"}
                  </span>
                </div>
                <input
                  type="text"
                  value={getHeaderDisplayValue(field)}
                  readOnly
                  disabled
                  className="pf-header-readonly-input"
                />
                <div className="pf-header-meta-row">
                  <span>{HEADER_SOURCE_LABELS[field.valueSource] || field.valueSource || "Managed source"}</span>
                  {field.required && <span>Required</span>}
                  {field.semanticId && <span>{field.semanticId}</span>}
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    );
  };

  const renderManagedComplianceSection = () => {
    const activeFacilities = Array.isArray(complianceContext.facilities) ? complianceContext.facilities : [];

    return (
      <div className="form-section pf-managed-section">
        <div className="section-header passport-header-static">
          <span className="section-title">Release Metadata</span>
          <span className="pf-header-locked-pill">Passport managed</span>
        </div>
        <div className="section-content">
          <p className="section-hint">
            These release-critical values are stored on each passport record. Use them for passport-specific operator identities and facility selection.
          </p>
          <div className="form-grid">
            <div className="form-group">
              <label htmlFor="economic-operator-id">Economic Operator Identifier</label>
              <input
                id="economic-operator-id"
                type="text"
                className="passport-model-input"
                value={formData.economic_operator_id || ""}
                placeholder="Enter the operator identifier for this passport"
                onChange={(e) => handleField("economic_operator_id", e.target.value)}
                disabled={isSaving || (mode === "edit" && isLoading)}
              />
              <div className="pf-managed-hint">Can differ per passport if a subsidiary or delegated operator should be identified here.</div>
            </div>
            <div className="form-group">
              <label htmlFor="economic-operator-scheme">Operator Identifier Scheme</label>
              <input
                id="economic-operator-scheme"
                type="text"
                className="passport-model-input"
                value={formData.economic_operator_identifier_scheme || ""}
                placeholder="Enter the identifier scheme used for this passport"
                onChange={(e) => handleField("economic_operator_identifier_scheme", e.target.value)}
                disabled={isSaving || (mode === "edit" && isLoading)}
              />
              <div className="pf-managed-hint">Examples: `VAT`, `EORI`, or the scheme required by your target regulation.</div>
            </div>
            <div className="form-group full-width">
              <label htmlFor="facility-id">Facility</label>
              <input
                id="facility-id"
                type="text"
                className="passport-model-input"
                value={formData.facility_id || ""}
                onChange={(e) => handleField("facility_id", e.target.value)}
                placeholder="Enter the facility identifier for this passport"
                disabled={isSaving || (mode === "edit" && isLoading)}
                list={activeFacilities.length ? "passport-facility-suggestions" : undefined}
              />
              {activeFacilities.length ? (
                <datalist id="passport-facility-suggestions">
                  {activeFacilities.map((facility) => {
                    const identifier = facility?.facility_identifier || "";
                    const displayName = facility?.display_name ? `${facility.display_name} (${identifier})` : identifier;
                    return <option key={identifier} value={identifier} label={displayName} />;
                  })}
                </datalist>
              ) : null}
              <div className="pf-managed-hint">
                {activeFacilities.length
                  ? "Enter a passport-specific facility identifier, or pick from the company’s active facility suggestions if helpful."
                  : "Enter the facility identifier for this passport. Batch and item battery passports require a facility before release."}
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  };

  if (isLoading || loadingType) return (
    <div className="createpass-page">
      <div className="loading" style={{ padding:60 }}>Loading passport…</div>
    </div>
  );

  const typeLabel = displayName || (passportType
    ? passportType.charAt(0).toUpperCase() + passportType.slice(1)
    : "");

  return (
    <div className="createpass-page">
      <header className="createpass-header">
        <button className="back-btn" onClick={() => navigate(`/dashboard/passports/${passportType}`)}>
          ← Back
        </button>
        <h1>{mode==="create" ? "Create New" : "Edit"} {typeLabel} Passport</h1>
      </header>

      <main className="createpass-main">
        <div className="createpass-container">
          {mode === "edit" && (
            <div className="edit-session-banner">
              <div className="edit-session-copy">
                <strong>Edit session notice:</strong> this edit session ends automatically after 12 hours of inactivity. Changes are logged only when you press <strong>Save Changes</strong>.
              </div>
              <div className="edit-session-meta">
                {activeEditors.length > 0
                  ? `${activeEditors.map((editor) => editor.name).join(", ")} ${activeEditors.length === 1 ? "is" : "are"} editing now`
                  : "Only you are editing right now"}
                {autoSaveState === "pending" && <span className="edit-session-status">Unsaved changes</span>}
                {autoSaveState === "saving" && <span className="edit-session-status">Saving…</span>}
                {autoSaveState === "saved" && lastSavedAt && <span className="edit-session-status">Saved</span>}
                {sessionExpired && <span className="edit-session-status">Session expired after inactivity</span>}
              </div>
            </div>
          )}

          {/* Identity row */}
          <div className="passport-identity-row">
            <div className="passport-field-group">
              <label htmlFor="productId">Serial Number</label>
              <input id="productId" type="text" value={productId}
                className="passport-model-input"
                placeholder="Enter serial number"
                onChange={e => { markDirty(); setProductId(e.target.value); }} disabled={isSaving}
                required />
            </div>
            <div className="passport-field-group">
              <label htmlFor="modelName">Model Name</label>
              <input id="modelName" type="text" value={modelName}
                className="passport-model-input"
                placeholder="Enter model name (optional)"
                onChange={e => { markDirty(); setModelName(e.target.value); }} />
            </div>
            <div className="passport-field-group">
              <label>Passport Type</label>
              <div className="type-badge" style={{ padding:"11px 14px", display:"inline-block" }}>
                {typeLabel.toUpperCase()}
              </div>
            </div>
          </div>

          {templateName && (
            <div className="pf-template-banner">
              <span className="pf-template-banner-icon">📋</span>
              <span>
                Creating from template <strong>{templateName}</strong>.
                Fields marked <strong>📌 Model data</strong> are pre-filled and locked.
              </span>
            </div>
          )}
          <div className="pf-governance-panel">
            Field confidentiality, access audiences, and update authority are set on the passport type by admins.
            This form shows those governance rules for each field, but editors cannot change them per passport record.
          </div>
          {error && <div className="alert alert-error" role="alert">{error}</div>}
          {success && <div className="alert alert-success" role="status" aria-live="polite">{success}</div>}

          <form onSubmit={handleSubmit} className="createpass-form">
            {renderManagedComplianceSection()}
            {renderPassportHeaderSection()}

            {sectionKeys.map(sk => {
              const section = SECTIONS[sk];
              const sectionContentId = `passport-section-${sk}`;
              return (
                <div key={sk} className="form-section">
                  <button
                    type="button"
                    className="section-header"
                    onClick={() => toggle(sk)}
                    aria-expanded={!!expanded[sk]}
                    aria-controls={sectionContentId}
                  >
                    <span className="section-title">{section.label}</span>
                    <span className={`toggle-icon${expanded[sk]?" expanded":""}`}>▼</span>
                  </button>
                  {expanded[sk] && (
                    <div id={sectionContentId} className="section-content">
                      {sk==="compliance" && (
                        <p className="section-hint">
                          Upload official PDF documents. Stored securely and shown in the passport viewer.
                        </p>
                      )}
                      <div className="form-grid">
                        {section.fields.map(f => {
                          const isLocked = mode === "create" && modelDataKeys.has(f.key);
                          return (
                            <div key={f.key}
                              className={`form-group${f.type==="textarea"||f.type==="file"?" full-width":""}${isLocked?" form-group-locked":""}`}>
                              {f.type !== "boolean" && (
                                <label htmlFor={f.type==="file" ? `f-${f.key}` : f.key}>
                                  {f.label}
                                  {isLocked && <span className="pf-model-badge">📌 Model data</span>}
                                </label>
                              )}
                              {renderField(f)}
                            </div>
                          );
                        })}
                      </div>
                    </div>
                  )}
                </div>
              );
            })}

            <div className="form-actions">
              <button type="button" className="cancel-btn"
                onClick={() => navigate(`/dashboard/passports/${passportType}`)} disabled={isSaving}>
                Cancel
              </button>
              <button type="submit" className="submit-btn" disabled={isSaving}>
                {isSaving ? "Saving…" : mode==="create" ? "Create Passport" : "Save Changes"}
              </button>
            </div>
          </form>
        </div>
      </main>

      <footer className="createpass-footer">
        <p>© 2024 Digital Product Passport System.</p>
      </footer>

      {/* ── Repository PDF Picker ── */}
      {repoPicker && (
        <RepositoryPicker
          token={token}
          companyId={effectiveCompanyId}
          onSelect={(url) => { handleField(repoPicker, url); setRepoPicker(null); }}
          onClose={() => setRepoPicker(null)}
        />
      )}

      {/* ── Symbol Picker ── */}
      {symbolPicker && (
        <div className="rp-overlay" onClick={e => e.target === e.currentTarget && setSymbolPicker(null)}>
          <div className="rp-modal" role="dialog" aria-modal="true" aria-labelledby="symbol-picker-title">
            <div className="rp-modal-header">
              <h3 id="symbol-picker-title">🔣 Pick a Symbol</h3>
              <button type="button" className="rp-close-btn" onClick={() => setSymbolPicker(null)} aria-label="Close symbol picker">✕</button>
            </div>
            <div className="pf-symbol-grid">
              {symbols.length === 0 ? (
                <div className="rp-empty">No symbols in repository yet.</div>
              ) : symbols.map(s => (
                <button
                  key={s.id}
                  type="button"
                  className={`pf-symbol-item${formData[symbolPicker] === s.file_url ? " selected" : ""}`}
                  onClick={() => { handleField(symbolPicker, s.file_url); setSymbolPicker(null); }}
                >
                  <img src={s.file_url} alt={s.name} className="pf-symbol-grid-img" />
                  <span className="pf-symbol-name">{s.name}</span>
                  {s.category && <span className="pf-symbol-cat">{s.category}</span>}
                </button>
              ))}
            </div>
            <div className="rp-footer">
              <button type="button" className="rp-cancel-btn" onClick={() => setSymbolPicker(null)}>Cancel</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default PassportForm;
